### ISSUE TITLE
VS 2010+ support

### ISSUE THREAD

**Issue by pravic** [MISoftware/OmniView#1]
Many people working in VS 2010 (2015 is too slowly, for example). Can you support earlier VS versions (2010-2013) too, like most of extensions does? It would be great.

**Comment by midiway** [comment]
yes, surely, but may take a while =/

**Comment by midiway** [comment]
I added VS2013 support :+1:
VS 2013 is much faster than 2015, a good alternative if you are having performance issues..

**Comment by pravic** [comment]
Thanks, despite of I haven't 2013 :laughing:

**Comment by pravic** [comment]
So, 2010 is supported now?

**Comment by midiway** [comment]
no, sorry, how do you know that many people are working with Sciter in VS2010?
