### ISSUE TITLE
Missing Microsoft.VisualStudio.Text.UI.Wpf

### ISSUE THREAD

**Issue by pravic** [MISoftware/OmniView#1]
VS 2015 unable to start after installing this extension. It shows an error about missing reference Microsoft.VisualStudio.Text.UI.Wpf, Version=15.0.0.0.

**Comment by midiway** [comment]
Sorry, fixed. Install version 2.6: https://visualstudiogallery.msdn.microsoft.com/d9c43bc6-8e1a-45a9-a095-67d7332d7e98?redir=0

If you are unable to start VS, start in /SafeMode - https://msdn.microsoft.com/en-us/library/ms241278.aspx
