### ISSUE TITLE
The extension did not install

### ISSUE THREAD

**Issue by acrlink** [MISoftware/OmniView#2]
### Installed product versions
- Visual Studio: 2013 Premium - Update 5
- This extension: 1.5

### Description
I tried to install the extension and showed the following message: 
- This extension is not installable on any currently instaled products.

Thanks in advance.

**Comment by midiway** [comment]
Well, works for me, even in a fresh installed VS2015 in my VM.
Plz, test if it still fails with version 1.6 that I've just released.
Check if your VS 2013/2015 has update 5 and update 2, respectively.
